name: Build and Release

on:
  push:
    tags:
      - 'v*'  

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt  

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed --icon=src/img/idbuddy.ico --name idBuddy --hidden-import=PIL main.py
        # Inkludera Pillow och sätt namnet på .exe till idBuddy

      - name: List dist directory  # Felsökning för att lista alla filer i dist/
        run: dir dist

      - name: Upload artifact (exe)
        uses: actions/upload-artifact@v3
        with:
          name: exe-file
          path: dist/idBuddy.exe  

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: exe-file

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: idBuddy.exe  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
