name: Build and Release

on:
    push:
        tags:
          - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Generate version.txt  
        run: |
          python ./config/generate_version_file.py

      - name: Generate spec file  
        run: |
          python ./config/generate_spec_file.py

      - name: List project directory for debugging  
        run: dir

      - name: Build executable with PyInstaller  
        run: |
          pyinstaller ./main.spec

      - name: List dist directory
        run: dir dist

      - name: Upload artifact (idBuddy directory)
        uses: actions/upload-artifact@v3
        with:
          name: idBuddy-folder
          path: dist/idBuddy

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: idBuddy-folder

      - name: Create a zip file of the folder
        run: |
            Compress-Archive -Path dist/idBuddy -DestinationPath idBuddy.zip
        shell: pwsh

      - name: Upload zip to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: idBuddy.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

